# Generated by Django 6.0.3 on 2026-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='original_pdf',
        ),
        migrations.RemoveField(
            model_name='document',
            name='signed_pdf',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='signed/'),
        ),
    ]
